import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#ffd3cc",
        "primary-container": "#0f6e56",
        "inverse-on-surface": "#eef2ee",
        "on-tertiary-fixed-variant": "#743329",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "secondary-container": "#83f5c6",
        "primary-fixed-dim": "#84d6b9",
        "on-primary-container": "#9aedcf",
        "on-primary-fixed-variant": "#00513e",
        "surface-container-high": "#e5e9e5",
        "tertiary-fixed-dim": "#ffb4a8",
        "background": "#f7faf6",
        "on-tertiary": "#ffffff",
        "secondary": "#006c4e",
        "on-background": "#181d1a",
        "primary": "#005440",
        "on-primary": "#ffffff",
        "surface-bright": "#f7faf6",
        "on-surface-variant": "#3f4944",
        "surface-container": "#ebefeb",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e0e3e0",
        "tertiary": "#78352b",
        "surface-variant": "#e0e3e0",
        "tertiary-fixed": "#ffdad4",
        "on-secondary-container": "#007151",
        "surface": "#f7faf6",
        "surface-container-low": "#f1f4f1",
        "secondary-fixed-dim": "#68dbae",
        "on-secondary-fixed-variant": "#00513a",
        "on-tertiary-fixed": "#3b0804",
        "inverse-surface": "#2d312f",
        "on-error-container": "#93000a",
        "outline": "#6f7a74",
        "surface-tint": "#086b53",
        "outline-variant": "#bec9c3",
        "on-surface": "#181d1a",
        "primary-fixed": "#a0f3d4",
        "surface-dim": "#d7dbd7",
        "secondary-fixed": "#86f8c9",
        "on-secondary-fixed": "#002115",
        "tertiary-container": "#954c41",
        "inverse-primary": "#84d6b9",
        "on-primary-fixed": "#002117",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "32px",
        base: "4px",
        sm: "16px",
        xs: "8px",
        "container-max": "1280px",
        gutter: "20px",
        xl: "48px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
} satisfies Config;
